"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
"""
def even_sum(seq):
	sum = 0
	for x in seq:
		if x % 2 == 0:
			sum += x
	return sum

def fib(num):
	seq = []
	dig = num - 1
	while num < 4000000:
		fib  = dig + num
		seq.append(fib)
		dig  = num
		num = fib
	print(even_sum(seq))

fib(1)


		
		



